"use client";

import { useEffect, useState } from "react";
import { ChevronDown, ExternalLink, Eye, Globe, Send, X } from "lucide-react";
import RevisionControls, { type RevisionItem } from "./RevisionControls";
import ChangesView from "./ChangesView";
import type { DiffGroup } from "@/lib/text-diff";

interface ContentPr {
  number: number;
  title: string;
  body: string | null;
  url: string;
  created_at: string;
  previewUrl: string | null;
  pages: string[];
  files: { name: string; status: string; additions: number; deletions: number }[];
  revisions: RevisionItem[];
  changes: DiffGroup[];
}

// The agent's PR description, minus its trailing "Generated by" footer.
function summary(body: string | null) {
  if (!body) return "";
  return body.split(/\n---\n|\n🤖/)[0].trim();
}

export default function ContentPrsPanel() {
  const [prs, setPrs] = useState<ContentPr[] | null>(null);
  const [configured, setConfigured] = useState(true);
  const [openNumber, setOpenNumber] = useState<number | null>(null);
  const [textOpen, setTextOpen] = useState<number | null>(null);
  const [busy, setBusy] = useState<number | null>(null);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");

  async function fetchPrs() {
    const res = await fetch("/api/admin/content-prs");
    const data = await res.json();
    if (!res.ok) throw new Error(data.error || "Failed to load website changes");
    return data as { configured: boolean; prs: ContentPr[] };
  }

  async function load() {
    try {
      const data = await fetchPrs();
      setConfigured(data.configured);
      setPrs(data.prs);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load website changes");
    }
  }

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const data = await fetchPrs();
        if (cancelled) return;
        setConfigured(data.configured);
        setPrs(data.prs);
        // Email links point at #pr-<number> — open that one.
        const hashNumber = Number(window.location.hash.replace("#pr-", ""));
        if (hashNumber && data.prs.some((p) => p.number === hashNumber)) setOpenNumber(hashNumber);
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : "Failed to load website changes");
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);


  // While a revision is pending or running, check back every 20s so the
  // card updates on its own when the agent finishes.
  const revising = prs?.some((x) => x.revisions?.some((r) => r.status === "pending" || r.status === "in_progress"));
  useEffect(() => {
    if (!revising) return;
    const timer = setInterval(() => {
      load();
    }, 20_000);
    return () => clearInterval(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [revising]);

  async function publish(pr: ContentPr) {
    const pendingRevision = pr.revisions.some((r) => r.status === "pending" || r.status === "in_progress");
    const question = pendingRevision
      ? `A revision you asked for is still in progress. Publish "${pr.title}" as it is now anyway?`
      : `Publish "${pr.title}" to the live website?`;
    if (!confirm(question)) return;
    setBusy(pr.number);
    setError("");
    setNotice("");
    const res = await fetch(`/api/admin/content-prs/${pr.number}`, { method: "POST" });
    const data = await res.json().catch(() => ({}));
    setBusy(null);
    if (!res.ok) {
      setError(data.error || "Failed to publish");
      return;
    }
    setNotice(
      `Published. The live site updates in about 2 minutes${data.keywordsCompleted ? ` — ${data.keywordsCompleted} keyword(s) marked done` : ""}.`
    );
    load();
  }

  async function reject(pr: ContentPr) {
    if (!confirm(`Reject "${pr.title}"? Nothing goes live, and its keywords go back in the queue for the agent to redo.`)) return;
    setBusy(pr.number);
    setError("");
    setNotice("");
    const res = await fetch(`/api/admin/content-prs/${pr.number}`, { method: "DELETE" });
    const data = await res.json().catch(() => ({}));
    setBusy(null);
    if (!res.ok) {
      setError(data.error || "Failed to reject");
      return;
    }
    setNotice("Rejected. Its keywords are back in the queue.");
    load();
  }

  return (
    <div>
      <h2 className="text-lg font-semibold text-gray-900">Website changes</h2>
      <p className="mt-1 text-sm text-gray-500">
        New and improved pages from the content agent. Preview them, then publish or reject.
      </p>

      {error && <p className="mt-4 text-sm text-red-600">{error}</p>}
      {notice && <p className="mt-4 rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-700">{notice}</p>}

      <div className="mt-4 space-y-4">
        {!configured ? (
          <p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">
            GitHub isn&apos;t connected yet &mdash; add a <code>GITHUB_TOKEN</code> environment variable in Vercel to review
            and publish website changes here.
          </p>
        ) : !prs ? (
          <p className="text-sm text-gray-500">Loading…</p>
        ) : prs.length === 0 ? (
          <div className="rounded-xl border border-dashed border-gray-300 bg-white py-12 text-center">
            <Globe className="mx-auto h-10 w-10 text-gray-300" />
            <p className="mt-3 font-semibold text-gray-700">No website changes waiting</p>
            <p className="mt-1 text-sm text-gray-500">When the content agent builds pages for your keywords, they show up here.</p>
          </div>
        ) : (
          prs.map((pr) => {
            const open = openNumber === pr.number;
            return (
              <div key={pr.number} id={`pr-${pr.number}`} className="scroll-mt-6 rounded-xl border border-gray-200 bg-white p-5">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div className="min-w-0">
                    <p className="text-base font-semibold text-gray-900">{pr.title}</p>
                    <p className="mt-1 text-xs text-gray-400">
                      {pr.files.length} file{pr.files.length === 1 ? "" : "s"} changed · prepared{" "}
                      {new Date(pr.created_at).toLocaleString("en-US", {
                        month: "short",
                        day: "numeric",
                        hour: "numeric",
                        minute: "2-digit",
                      })}
                    </p>
                  </div>
                  <div className="flex shrink-0 items-center gap-2">
                    <button
                      onClick={() => publish(pr)}
                      disabled={busy === pr.number}
                      className="flex items-center gap-1.5 rounded-md bg-green-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-green-700 disabled:opacity-50"
                    >
                      <Send className="h-4 w-4" />
                      {busy === pr.number ? "Working…" : "Publish"}
                    </button>
                    <button
                      onClick={() => reject(pr)}
                      disabled={busy === pr.number}
                      className="flex items-center gap-1.5 rounded-md border border-gray-200 px-3 py-1.5 text-sm font-medium text-red-600 hover:bg-red-50 disabled:opacity-50"
                    >
                      <X className="h-4 w-4" />
                      Reject
                    </button>
                  </div>
                </div>

                {pr.pages.length > 0 && (
                  <div className="mt-4">
                    <p className="text-xs font-semibold uppercase tracking-wide text-gray-400">
                      {pr.previewUrl ? "Preview the pages before publishing" : "Pages affected (preview still building)"}
                    </p>
                    <div className="mt-2 flex flex-wrap gap-2">
                      {pr.pages.map((path) =>
                        pr.previewUrl ? (
                          <a
                            key={path}
                            href={`${pr.previewUrl}${path}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="flex items-center gap-1.5 rounded-full border border-brand/30 bg-brand/5 px-3 py-1 text-sm font-medium text-brand hover:bg-brand/10"
                          >
                            <Eye className="h-3.5 w-3.5" />
                            {path}
                          </a>
                        ) : (
                          <span key={path} className="rounded-full border border-gray-200 px-3 py-1 text-sm text-gray-500">
                            {path}
                          </span>
                        )
                      )}
                    </div>
                  </div>
                )}

                {pr.changes.length > 0 && (
                  <div className="mt-4">
                    <button
                      onClick={() => setTextOpen(textOpen === pr.number ? null : pr.number)}
                      className="flex items-center gap-1 text-sm font-semibold text-brand hover:underline"
                    >
                      <ChevronDown className={`h-4 w-4 transition-transform ${textOpen === pr.number ? "rotate-180" : ""}`} />
                      {textOpen === pr.number ? "Hide the wording changes" : "Read the wording changes"}
                    </button>
                    {textOpen === pr.number && (
                      <div className="mt-2 rounded-lg border border-gray-200 p-3">
                        <p className="mb-3 text-xs text-gray-500">
                          Everything this update changes compared with the live site, including any revisions you asked for.
                        </p>
                        <ChangesView groups={pr.changes} />
                      </div>
                    )}
                  </div>
                )}

                <RevisionControls endpoint={`/api/admin/content-prs/${pr.number}/revise`} revisions={pr.revisions} onChanged={load} />

                <button
                  onClick={() => setOpenNumber(open ? null : pr.number)}
                  className="mt-4 flex items-center gap-1 text-sm font-medium text-brand hover:underline"
                >
                  <ChevronDown className={`h-4 w-4 transition-transform ${open ? "rotate-180" : ""}`} />
                  {open ? "Hide details" : "What the agent did"}
                </button>

                {open && (
                  <div className="mt-3 space-y-3 border-t border-gray-100 pt-3">
                    <p className="whitespace-pre-wrap text-sm text-gray-700">{summary(pr.body)}</p>
                    <ul className="space-y-1 text-xs text-gray-500">
                      {pr.files.map((f) => (
                        <li key={f.name}>
                          <span className="font-mono">{f.name}</span>{" "}
                          <span className="text-green-600">+{f.additions}</span>{" "}
                          <span className="text-red-500">−{f.deletions}</span>
                        </li>
                      ))}
                    </ul>
                    <a
                      href={pr.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-1 text-xs text-gray-400 hover:underline"
                    >
                      View on GitHub <ExternalLink className="h-3 w-3" />
                    </a>
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
